ADDED:Employee Management System
msindia-learning/2024-BATCH-I pull request #75
Opened 2024-04-05 10:05 UTC by AKSHAYAPALCHAMY-P

2024-04-05 12:54 UTC, msindia-learning commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/js/adminLogin.js
> +    let adminEmail = 'admin@gmail.com';
Change variable names as strOriginalAdminEmail

2024-04-05 12:54 UTC, msindia-learning commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/js/adminLogin.js
> +    let adminEmail = 'admin@gmail.com';
Follow the same for adminPassword

2024-04-05 12:54 UTC, msindia-learning commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/views/adminlogin.html
Change file name to AdminLogin.html

2024-04-05 12:55 UTC, msindia-learning commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/js/adminLogin.js
Add filename as AdminLogin.js

2024-04-05 13:00 UTC, AKSHAYAPALCHAMY-P commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/js/adminLogin.js
> +    let adminEmail = 'admin@gmail.com';
done

2024-04-05 13:01 UTC, AKSHAYAPALCHAMY-P commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/views/adminlogin.html
done

2024-04-09 05:20 UTC, ManiRaj-021199 requested changes
Please have a look

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/js/AdminLogin.js
> +const ADMIN_EMAIL = document.getElementById("loginEmail");
Good to see this naming.., 😊👌

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/js/adminLogin.js
> +    let adminEmail = 'admin@gmail.com';
Please check.. Not yet resolved..,

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Views/AdminLogin.html
> +    <div>
Where is the container div?

```
<div id="1"></div>
<div id="2"></div>

<div id="container">
  <div id="1"></div>
  <div id="2"></div>
</div>
```

Which one will you choose?

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +    const saveButton = document.getElementById("saveButton");
const naming rule - ALL_CAPS

SAVE_BUTTON

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +    const saveButton = document.getElementById("saveButton");
Move document.getElementById to global declaration.

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +    saveButton.addEventListener("click", function()
Why addEventListener -> use onclick instead

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +        const genderElement = document.querySelector('input[name="gender"]:checked');
move all const to global.

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +        //if (!genderElement) {
remove commented codes

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +        let details = JSON.parse(localStorage.getItem("Details")) || [];
Why everywhere getting and parsing localstorage values? Think about alternative solutions? 😊

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +let displayMethods = {};
EmployeeDetailMethods

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +    const saveButton = document.getElementById("saveButton");
Give meaningful name - AddEmployee

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +        document.getElementById("employeeForm").reset();
Nice 😊

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +                    return `<li>${detail["Employee Name"]} - ${detail["Employee Age"]} - ${detail["Employee Address"]} - ${detail["Employee Qualification"]} - ${detail["Employee Position"]} - ${detai
Hardcoded string.. Any other ways to achieve this?

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +        document.getElementById('EmpName').value = employee["Employee Name"];
Duplicate code. Use global value instead.

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +        {
This implementation looks nice. 😊

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +        localStorage.setItem("Details", JSON.stringify(details));
Give proper name - Details -> EmployeeDetails

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +        saveButton.removeEventListener("click", displayMethods.updateEmployee);
Move this logic to separate function

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/JS/EmployeeDetails.js
> +document.addEventListener("DOMContentLoaded", function()
All methods are inside DOMContentLoaded -> Wrong approach.
Just call the function which is require to execute after page rendered..,

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Assets/js/AdminLogin.js
> +        alert("Login Successful!");
Do not use hardcoded string

2024-04-09 05:20 UTC, ManiRaj-021199 commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/views/adminlogin.html
Change file name - AdminLogin.html

2024-04-09 06:00 UTC, AKSHAYAPALCHAMY-P commented on AkshayaP/00 - Projects/04-Frontend Projects/Employee Management System/Views/AdminLogin.html
> +    <div>
2 nd one.

2024-04-09 10:22 UTC, ManiRaj-021199 commented
Files not updated properly.

2024-04-09 10:22 UTC, closed without merging